<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('App - Gerenciador de Sites - Sisdeve - Sistema em Desenvolvimento') ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/inputmask-plugin.js')
        ->prependFile($this->basePath() . '/js/scripts.js')
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>

</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('admin') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <?php if($this->UserIdentity("Admin")): ?>
                    <li <?php echo $this->menuAtivo($this->url('admin')); ?>><a href="<?php echo $this->url('admin') ?>"><?php echo $this->translate('Home') ?></a></li>
                    <li <?php echo $this->menuAtivo($this->url('admin-admin')); ?>><a href="<?php echo $this->url('admin-admin') ?>"><?php echo 'Admin' ?></a></li>
                    <?php /*<li <?php echo $this->menuAtivo($this->url('admin-arquivos')); ?>><a href="<?php echo $this->url('admin-arquivos') ?>"><?php echo 'Arquivos' ?></a></li> */ ?>
                    <li <?php echo $this->menuAtivo($this->url('admin-banners')); ?>><a href="<?php echo $this->url('admin-banners') ?>"><?php echo 'Banners' ?></a></li>
                    <li <?php echo $this->menuAtivo($this->url('admin-clientes')); ?>><a href="<?php echo $this->url('admin-clientes') ?>"><?php echo 'Clientes' ?></a></li>
                    <li <?php echo $this->menuAtivo($this->url('admin-contatos')); ?>><a href="<?php echo $this->url('admin-contatos') ?>"><?php echo 'Contatos' ?></a></li>
                    <li <?php echo $this->menuAtivo($this->url('admin-config')); ?>><a href="<?php echo $this->url('admin-config') ?>"><?php echo 'Configurações' ?></a></li>
                    <li <?php echo $this->menuAtivo($this->url('admin-news')); ?>><a href="<?php echo $this->url('admin-news') ?>"><?php echo 'News' ?></a></li>
                    <li <?php echo $this->menuAtivo($this->url('admin-parceiros')); ?>><a href="<?php echo $this->url('admin-parceiros') ?>"><?php echo 'Parceiros' ?></a></li>
                    <li <?php echo $this->menuAtivo($this->url('admin-servicos')); ?>><a href="<?php echo $this->url('admin-servicos') ?>"><?php echo 'Serviços' ?></a></li>
                    <li <?php echo $this->menuAtivo($this->url('admin-logout')); ?>><a href="<?php echo $this->url('admin-logout') ?>"><?php echo 'Logout' ?></a></li>
                <?php
                    else:
                ?>
                        <li <?php echo $this->menuAtivo($this->url('admin-auth')); ?>><a href="<?php echo $this->url('admin-auth') ?>"><?php echo 'Login' ?></a></li>
                <?php endif; ?>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
<div class="container">
    <?php echo $this->message(); ?>
    <?php echo $this->content; ?>
    <hr>
    <footer>
        <p>&copy; 2010 - <?php echo date('Y') ?> <span class="zf-green">by Sisdeve - Sistema em Desenvolvimento. </span> <?php echo $this->translate('All rights reserved.') ?></p>
    </footer>
</div> <!-- /container -->
<?php echo $this->inlineScript() ?>
</body>
</html>