<h3>Login</h3>

<br />

<?php if($this->error): ?>
    <div class="alert alert-danger">Usuário ou senha inválidos<button type="button" class="close" data-dismiss="alert">×</button></div>
<?php endif; ?>

<?php

$form = $this->form;
$form->setAttribute('action', $this->url('admin-auth', array('controller' => 'admin', 'action' => 'index')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();

?>