<?php

namespace Admin\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdminAdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminAdminRepository extends EntityRepository
{
    public function findByLogin($login,$senha)
    {
        $admin = $this->findOneByLogin($login);

        if($admin){
            $hashSenha = $admin->encryptSenha($senha);
            if($hashSenha == $admin->getSenha())
                return $admin;
            else
                return false;
        }
        return false;
    }
}
