<?php

namespace Admin\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdminContatosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminContatosRepository extends EntityRepository
{
}
