<?php

namespace Admin\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdminServicosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminServicosRepository extends EntityRepository
{
}
